name: Android CD

on:
  pull_request:
  push:
    branches:
      - master
      - develop
      - staging

jobs:
  apk-beta:
    name: Build apk master
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install fastlane
        run: brew install fastlane
      - name: Build APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk
